#+title: Material para un curso de Econometría 
#+author: Marcos Bujosa
#+LANGUAGE: es-es
#+OPTIONS: toc:nil

Transparencias y apuntes para impartir un curso introductorio de
econometría haciendo incapié en la interpretación geométrica de muchos
de los conceptos habituales de la probabilidad y la estadística.

- El material de clase está ordenado por lecciones:
  - La versión [[https://github.com/mbujosab/Ectr/blob/master/apuntes-Ectr-print.pdf][print]] contiene las transparencias junto con
    explicaciones y mucho más.
  - La versión [[https://github.com/mbujosab/Ectr/blob/master/apuntes-Ectr-handout.pdf][handout]] contiene una réplica de las transparencias que
    usaré con el proyector del aula.

La versión "handout" no sirve para estudiar, pero es útil para llevar
a clase y tener en papel lo que verá en la pantalla. En clase es más
útil escuchar las explicaciones, pensar en ellas y hacer preguntas que
copiar lo que aparece en la pantalla. Por ello le proporciono la
versión "handout" (para que tenga en papel lo que ve en pantalla y no
tenga que copiarlo).

#+macro: GPLv3 [[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

{{{GPLv3}}}

Notebooks de Jupiter [[https://mybinder.org/v2/gh/mbujosab/Ectr/master?labpath=Practicas%2FPython%2Fnotebooks][aquí]]
[[https://mybinder.org/v2/gh/mbujosab/Ectr/master?labpath=Practicas%2FPython%2Fnotebooks][ {{{GPLv3}}} ]]

